#!/usr/bin/bash
ln -s 7b_cp_dustbowl.bsp.bz2 ../../tf2c/maps/7b_cp_dustbowl.bsp.bz2
ln -s 7b_ctf_2fort.bsp.bz2 ../../tf2c/maps/7b_ctf_2fort.bsp.bz2
ln -s arena_1on1_wizard_duel_b1.bsp.bz2 ../../tf2c/maps/arena_1on1_wizard_duel_b1.bsp.bz2
ln -s balloon_race_v2b.bsp.bz2 ../../tf2c/maps/balloon_race_v2b.bsp.bz2
ln -s boss_big_shot_v6.bsp.bz2 ../../tf2c/maps/boss_big_shot_v6.bsp.bz2
ln -s boss_jevil_v5.bsp.bz2 ../../tf2c/maps/boss_jevil_v5.bsp.bz2
ln -s cp_1fort.bsp.bz2 ../../tf2c/maps/cp_1fort.bsp.bz2
ln -s cp_degrootkeep_mvm_v4.bsp.bz2 ../../tf2c/maps/cp_degrootkeep_mvm_v4.bsp.bz2
ln -s cp_dustcity.bsp.bz2 ../../tf2c/maps/cp_dustcity.bsp.bz2
ln -s cp_fnaf_rc1.bsp.bz2 ../../tf2c/maps/cp_fnaf_rc1.bsp.bz2
ln -s cp_lwobtsud.bsp.bz2 ../../tf2c/maps/cp_lwobtsud.bsp.bz2
ln -s cp_orange_x3.bsp.bz2 ../../tf2c/maps/cp_orange_x3.bsp.bz2
ln -s ctf_2fort5_v2.bsp.bz2 ../../tf2c/maps/ctf_2fort5_v2.bsp.bz2
ln -s ctf_2fort_aeuhhh.bsp.bz2 ../../tf2c/maps/ctf_2fort_aeuhhh.bsp.bz2
ln -s ctf_2fort_classic.bsp.bz2 ../../tf2c/maps/ctf_2fort_classic.bsp.bz2
ln -s ctf_2fort_classic_redux.bsp.bz2 ../../tf2c/maps/ctf_2fort_classic_redux.bsp.bz2
ln -s ctf_2fort_mvm_v4.bsp.bz2 ../../tf2c/maps/ctf_2fort_mvm_v4.bsp.bz2
ln -s ctf_2fort_switched.bsp.bz2 ../../tf2c/maps/ctf_2fort_switched.bsp.bz2
ln -s ctf_badlands_2006_rc1.bsp.bz2 ../../tf2c/maps/ctf_badlands_2006_rc1.bsp.bz2
ln -s ctf_circusfunny.bsp.bz2 ../../tf2c/maps/ctf_circusfunny.bsp.bz2
ln -s ctf_convoy_v2.bsp.bz2 ../../tf2c/maps/ctf_convoy_v2.bsp.bz2
ln -s ctf_facing_worlds_1999c.bsp.bz2 ../../tf2c/maps/ctf_facing_worlds_1999c.bsp.bz2
ln -s ctf_facing_worlds_2011.bsp.bz2 ../../tf2c/maps/ctf_facing_worlds_2011.bsp.bz2
ln -s ctf_half2fort_halfturbine.bsp.bz2 ../../tf2c/maps/ctf_half2fort_halfturbine.bsp.bz2
ln -s ctf_minetest2.bsp.bz2 ../../tf2c/maps/ctf_minetest2.bsp.bz2
ln -s ctf_minetest.bsp.bz2 ../../tf2c/maps/ctf_minetest.bsp.bz2
ln -s ctf_orangeforts.bsp.bz2 ../../tf2c/maps/ctf_orangeforts.bsp.bz2
ln -s ctf_tf2_2fort_2003.bsp.bz2 ../../tf2c/maps/ctf_tf2_2fort_2003.bsp.bz2
ln -s dm_halo_bloodgulch.bsp.bz2 ../../tf2c/maps/dm_halo_bloodgulch.bsp.bz2
ln -s dm_longest_yard.bsp.bz2 ../../tf2c/maps/dm_longest_yard.bsp.bz2
ln -s dr_bazinga_remake_b1b.bsp.bz2 ../../tf2c/maps/dr_bazinga_remake_b1b.bsp.bz2
ln -s dr_boomershooter_b8c.bsp.bz2 ../../tf2c/maps/dr_boomershooter_b8c.bsp.bz2
ln -s dr_hyvat_herrat_b5.bsp.bz2 ../../tf2c/maps/dr_hyvat_herrat_b5.bsp.bz2
ln -s dr_shadow_moses_v3.bsp.bz2 ../../tf2c/maps/dr_shadow_moses_v3.bsp.bz2
ln -s dr_simpsons_ct_final2.bsp.bz2 ../../tf2c/maps/dr_simpsons_ct_final2.bsp.bz2
ln -s dr_simpsons_redux.bsp.bz2 ../../tf2c/maps/dr_simpsons_redux.bsp.bz2
ln -s dr_supermario64_v6b.bsp.bz2 ../../tf2c/maps/dr_supermario64_v6b.bsp.bz2
ln -s dr_tim_allen_v2b.bsp.bz2 ../../tf2c/maps/dr_tim_allen_v2b.bsp.bz2
ln -s duality_2012_b1.bsp.bz2 ../../tf2c/maps/duality_2012_b1.bsp.bz2
ln -s gg_dust2_dmvm.bsp.bz2 ../../tf2c/maps/gg_dust2_dmvm.bsp.bz2
ln -s htf_city17_v2.bsp.bz2 ../../tf2c/maps/htf_city17_v2.bsp.bz2
ln -s htf_doom2_fix.bsp.bz2 ../../tf2c/maps/htf_doom2_fix.bsp.bz2
ln -s htf_sm64whompsfortress.bsp.bz2 ../../tf2c/maps/htf_sm64whompsfortress.bsp.bz2
ln -s mg_buses_from_hell_redux.bsp.bz2 ../../tf2c/maps/mg_buses_from_hell_redux.bsp.bz2
ln -s mvm_ma_ep10_3_v4.bsp.bz2 ../../tf2c/maps/mvm_ma_ep10_3_v4.bsp.bz2
ln -s mvm_ma_ep10b_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep10b_3_v3.bsp.bz2
ln -s mvm_ma_ep11_3_v5.bsp.bz2 ../../tf2c/maps/mvm_ma_ep11_3_v5.bsp.bz2
ln -s mvm_ma_ep12_3_v6.bsp.bz2 ../../tf2c/maps/mvm_ma_ep12_3_v6.bsp.bz2
ln -s mvm_ma_ep12b1_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep12b1_3_v3.bsp.bz2
ln -s mvm_ma_ep12b2_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep12b2_3_v3.bsp.bz2
ln -s mvm_ma_ep12b3_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep12b3_3_v3.bsp.bz2
ln -s mvm_ma_ep13_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep13_3_v3.bsp.bz2
ln -s mvm_ma_ep1_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep1_3_v3.bsp.bz2
ln -s mvm_ma_ep14_3_v5.bsp.bz2 ../../tf2c/maps/mvm_ma_ep14_3_v5.bsp.bz2
ln -s mvm_ma_ep15_3_v5.bsp.bz2 ../../tf2c/maps/mvm_ma_ep15_3_v5.bsp.bz2
ln -s mvm_ma_ep16_3_v4.bsp.bz2 ../../tf2c/maps/mvm_ma_ep16_3_v4.bsp.bz2
ln -s mvm_ma_ep16b_3_v6.bsp.bz2 ../../tf2c/maps/mvm_ma_ep16b_3_v6.bsp.bz2
ln -s mvm_ma_ep2_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep2_3_v3.bsp.bz2
ln -s mvm_ma_ep3_3_v5.bsp.bz2 ../../tf2c/maps/mvm_ma_ep3_3_v5.bsp.bz2
ln -s mvm_ma_ep4_3_v4.bsp.bz2 ../../tf2c/maps/mvm_ma_ep4_3_v4.bsp.bz2
ln -s mvm_ma_ep5_3_v5.bsp.bz2 ../../tf2c/maps/mvm_ma_ep5_3_v5.bsp.bz2
ln -s mvm_ma_ep6_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep6_3_v3.bsp.bz2
ln -s mvm_ma_ep7_3_v3.bsp.bz2 ../../tf2c/maps/mvm_ma_ep7_3_v3.bsp.bz2
ln -s mvm_ma_ep8_3_v4.bsp.bz2 ../../tf2c/maps/mvm_ma_ep8_3_v4.bsp.bz2
ln -s mvm_ma_ep9_3_v4.bsp.bz2 ../../tf2c/maps/mvm_ma_ep9_3_v4.bsp.bz2
ln -s my_world_x9b.bsp.bz2 ../../tf2c/maps/my_world_x9b.bsp.bz2
ln -s onett_source_v6.bsp.bz2 ../../tf2c/maps/onett_source_v6.bsp.bz2
ln -s pd_steamed_hams_final.bsp.bz2 ../../tf2c/maps/pd_steamed_hams_final.bsp.bz2
ln -s pl_badwater_mvm_v4.bsp.bz2 ../../tf2c/maps/pl_badwater_mvm_v4.bsp.bz2
ln -s pl_casserole_rc3.bsp.bz2 ../../tf2c/maps/pl_casserole_rc3.bsp.bz2
ln -s plr_2fort_exe.bsp.bz2 ../../tf2c/maps/plr_2fort_exe.bsp.bz2
ln -s plr_2xhighertower_v2.bsp.bz2 ../../tf2c/maps/plr_2xhighertower_v2.bsp.bz2
ln -s pl_retawdab.bsp.bz2 ../../tf2c/maps/pl_retawdab.bsp.bz2
ln -s plr_upward_rc3.bsp.bz2 ../../tf2c/maps/plr_upward_rc3.bsp.bz2
ln -s pl_simpson_house_a7.bsp.bz2 ../../tf2c/maps/pl_simpson_house_a7.bsp.bz2
ln -s pl_simpson_house_r_b2.bsp.bz2 ../../tf2c/maps/pl_simpson_house_r_b2.bsp.bz2
ln -s pl_slopandslime_b2.bsp.bz2 ../../tf2c/maps/pl_slopandslime_b2.bsp.bz2
ln -s pl_upward_abandoned.bsp.bz2 ../../tf2c/maps/pl_upward_abandoned.bsp.bz2
ln -s rd_asteroid_redux_b1.bsp.bz2 ../../tf2c/maps/rd_asteroid_redux_b1.bsp.bz2
ln -s sd_turbine_a3a.bsp.bz2 ../../tf2c/maps/sd_turbine_a3a.bsp.bz2
ln -s vsh_facility_rc2.bsp.bz2 ../../tf2c/maps/vsh_facility_rc2.bsp.bz2
ln -s vsh_halepizza.bsp.bz2 ../../tf2c/maps/vsh_halepizza.bsp.bz2
ln -s vsh_natural_halestorm.bsp.bz2 ../../tf2c/maps/vsh_natural_halestorm.bsp.bz2
ln -s wacky_races_v2.bsp.bz2 ../../tf2c/maps/wacky_races_v2.bsp.bz2
